nodes: 5
edge_density: 1.0 # fully connected
rounds: 10
model_name: "loan_defaulter"
data_path: "/Users/sidb/Development/DFL-Secure-Aggregation/src/training/data/loan_data.csv"
num_samples: 800
epochs: 10
batch_size: 20
aggregation: "fedavg"
malicious_proportion: 0.8
attack_type: "noise"
attack_strength: 100000